### ISSUE TITLE
Notice "command 'marucs-anime.insertDate' not found " while using hotkeys to insert text

### ISSUE THREAD

**Issue by moonlord09** [marcuscastelo/vscode-anime#1]
The newest version from VS Code Extension. Do I need to install other extension or sth to run this useful tool?

**Comment by marcuscastelo** [comment]
Sorry for the delay, after rebuilding the project it indeed is broken.
I have just regenerated the project and it worked again.

Soon I'll update it on the marketplace.

Thanks for opening this issue!

**Comment by moonlord09** [comment]
Thx 4 the fixing~
